{ "service" : 
	{ "name" : "GeoNames Webservices"
	, "description" : "A collection of webservices from GeoWeb"
	}
, "interface" :
	{ "protocol" : ["HTTP","GET"]
	, "type"	 : "JSONRPC"
	}
, "operations" : [
	{ "name" : "Ocean Names"
	, "parameters" : [
		{ "name" : "lat"
		, "type" : "RPCReal"
		},
		{ "name" : "lng"
		, "type" : "RPCReal"
		}]
	, "location" : "http://ws.geonames.org/oceanJSON"
	, "callType" : "RequestResponse"
	, "returnType" : "String"
	},
	{ "name" : "Country Code"
	, "parameters" : [
		{ "name" : "lat"
		, "type" : "RPCReal"
		},
		{ "name" : "lng"
		, "type" : "RPCReal"
		},
		{ "name" : "type"
		, "type" : "RPCString"
		}]
	, "location" : "http://ws.geonames.org/countryCode"
	, "callType" : "RequestResponse"
	, "returnType" : "String"	
	}]
}